### ISSUE TITLE
Can't install from PyPI

### ISSUE THREAD

**Issue by zgoda** [ethanhs/pynanosvg#2]
Linux x86-64, Python 3.6.5

First:

```
pip install -U pynanosvg
Collecting pynanosvg
  Downloading https://files.pythonhosted.org/packages/00/f2/6e232f502789722b570a62de03a44e292bc70678fe6c0490ccc52046012c/pynanosvg-0.2.0.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 852kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-iq7sx8bt/pynanosvg/setup.py", line 2, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
```

After manually installing Cython:

```
pip install -U pynanosvg
Collecting pynanosvg
  Using cached https://files.pythonhosted.org/packages/00/f2/6e232f502789722b570a62de03a44e292bc70678fe6c0490ccc52046012c/pynanosvg-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-95n_dl9k/pynanosvg/setup.py", line 27, in <module>
        ext_modules=cythonize(ext),
      File "/home/jazg/v/rms/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 897, in cythonize
        aliases=aliases)
      File "/home/jazg/v/rms/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 777, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/jazg/v/rms/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 102, in nonempty
        raise ValueError(error_msg)
    ValueError: 'svg/__init__.pyx' doesn't match any files
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-95n_dl9k/pynanosvg/
```

Update: installation from source works OK.

**Comment by emmatyping** [comment]
Oh, it appears I didn't add `install_requires` to my `setup.py`. Let me go fix that.

**Comment by emmatyping** [comment]
For now you can `pip install -U Cython` and it should work.

**Comment by zgoda** [comment]
2nd error is what I got after manually installing Cython.

**Comment by emmatyping** [comment]
That is really strange, the file should exist. I will have more time to fix this later today. Sorry for the trouble!

**Comment by zgoda** [comment]
Thanks, the library is awesome, no more fiddling with Cairo and rsvg to get rasterized svg into buffer (I'm feeding it into Pygame Image object -> https://gist.github.com/zgoda/16c4bb767a085743251503471c1faeb1)

**Comment by emmatyping** [comment]
Ah, silly me, the sdists don't include cython files. For now you can do `pip install --user git+https://github.com/ethanhs/pynanosvg.git` and it will install. I will make a new release soon.

**Comment by emmatyping** [comment]
`pip install pynanosvg` should work now.
